version: "3.9"

services:
  bot:
    build: .
    container_name: deadright-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN_TEST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
